---
- name: "Add hostgroup for {{ _hostgroup }} Servers"
  ipahostgroup:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ _hostgroup.name }}"
    host: "{{ _hostgroup.host | default(omit) }}"
    descriptiom: "{{ _hostgroup.descriptiom | default(omit) }}"
  loop: "{{ hostgroup_list }}"
  loop_control:
    loop_var: _hostgroup
