---
  - name: Add /bin/bash as sudoers command
    ipasudocmd:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: /bin/bash
      state: present

  - name: Add sudoers rule for superusers to be able to get a root shell on all hosts
    ipasudorule:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: allow-superusers_sudo-i
      allow_sudocmd:
      - /bin/bash
      sudooption: "!authenticate"
      group: superusers
      runasuser: root
      action: sudorule
      state: present
    tags: sudoers
