---
- hosts: ipaserver
  vars_files:
    - ./vars.yml
    - ./secrets.yml
  roles:
    - role: ipaserver
      state: present

  pre_tasks:
    - name: Copy cert files
      copy:
        src: "files/{{ item | basename }}"
        dest: "{{ item }}"
      loop:
        - "{{ ipaserver_dirsrv_cert_files }}"
        - "{{ ipaserver_http_cert_files }}"
        - "{{ external_ca_cert_file }}"

  post_tasks:

  - name: Disable host based firewall
    systemd:
      state: stopped
      enabled: no
      name: firewalld
