---
- hosts: ipareplicas
  vars_files:
    - ./vars.yml
    - ./secrets.yml

  roles:
    - role: ipareplica
      state: present
      tags: ipareplica

  pre_tasks:

    - name: Copy cert files
      copy:
        src: "files/{{ item | basename }}"
        dest: "{{ item }}"
      loop:
        - "{{ ipareplica_dirsrv_cert_files }}"
        - "{{ ipareplica_http_cert_files }}"
        - "{{ external_ca_cert_file }}"

    - name: Disable host based firewall
      systemd:
        state: stopped
        enabled: false
        name: firewalld
