---
  - name: Create host
    ipahost:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: "{{ item.name }}"
      ip_address: "{{ item.ip }}"
      state: present
    loop: "{{ sles_client }}"

  # Dirty, dirty hack
  - name: Create admin Kerberos Ticket
    shell: |
      export KRB5CCNAME=FILE:/tmp/krb5cc_sles-enrollment$$
      echo "{{ ipaadmin_password }}"|kinit admin
      ipa-getkeytab -s {{ ipaserver }} -p host/{{ item.name }}@{{ ipaserver_realm }} -k /tmp/{{ item.name }}.keytab
      kdestroy
    no_log: true
    loop: "{{ sles_client }}"

  - name: Fetch krb5.keytab
    fetch:
      src: /tmp/{{ item.name }}.keytab
      dest: files/
      flat: yes
    loop: "{{ sles_client }}"
