---
# tasks file for usergroup-mappings

- name: "Add IPA groups"
  ipagroup:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ _ugmap.ipagroup | default(_ugmap.name) }}"
    description: "{{ _ugmap.description }}"
  loop: "{{ usergroup_mappings }}"
  loop_control:
    loop_var: _ugmap

- name: "Add IPA external group {{ _ugmap.name }}_ext"
  ipagroup:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ _ugmap.name }}_ext"
    description: "{{ _ugmap.description }} (external)"
    external: yes
    externalmember: 
      - "{{ _ugmap.name }}@{{ windows_domain }}"
  loop: "{{ usergroup_mappings }}"
  loop_control:
    loop_var: _ugmap

- name: "Add AD group {{ _ugmap.name }} to IPA group {{ _ugmap.name }}"
  ipagroup:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ _ugmap.ipagroup | default(_ugmap.name) }}"
    group: "{{ _ugmap.name }}_ext"
  loop: "{{ usergroup_mappings }}"
  loop_control:
    loop_var: _ugmap
