---
- name: add hbac rules
  ipahbacrule:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ _hbrule.name }}"
    description: "{{ _hbrule.description }}"
    hostcategory: "{{ _hbrule.hostcategory }}"
    servicecategory: "{{ _hbrule.servicecategory | default('all') }}"
    group: "{{ _hbrule.group }}"
  loop: "{{ hbacrule_list }}"
  loop_control:
    loop_var: _hbrule
  when: _hbrule.hostcategory is defined

- name: add hbac rules
  ipahbacrule:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ _hbrule.name }}"
    description: "{{ _hbrule.description }}"
    hostgroup: "{{ _hbrule.hostgroup | default('') }}"
    servicecategory: "{{ _hbrule.servicecategory | default('all') }}"
    group: "{{ _hbrule.group }}"
  loop: "{{ hbacrule_list }}"
  loop_control:
    loop_var: _hbrule
  when: _hbrule.hostgroup is defined
