---
- name: add hbac rules
  ipahbacrule:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: "{{ _hbrule.name }}"
    description: "{{ _hbrule.description | default(omit)}}"
    group: "{{ _hbrule.group | default(omit)}}"
    hbacsvc: "{{ _hbrule.hbacsvc | default(omit) }}"
    hbacsvcgroup: "{{ _hbrule.hbacsvcgroup | default(omit) }}"
    host: "{{ _hbrule.host | default(omit) }}"
    hostcategory: "{{ _hbrule.hostcategory | default(omit)}}"
    hostgroup: "{{ _hbrule.hostgroup | default(omit) }}"
    servicecategory: "{{ _hbrule.servicecategory | default(omit) }}"
    state: "{{ _hbrule.state | default(omit) }}"
    user: "{{ _hbrule.user | default(omit) }}"
    usercategory: "{{ _hbrule.usercategory | default(omit) }}"
  loop: "{{ hbacrule_list }}"
  loop_control:
    loop_var: _hbrule
