---
  - name: Establish one-way Trust to Windows Domain "{{ windows_realm }}"
    ipatrust:       
      realm: "{{ windows_realm }}"
      trust_secret: "{{ trust_secret }}"
      two_way: false
      state: present
