---
  - name: Add user hmuster
    ipauser:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: jdoe
      first: Jane
      last: Doe
      password: "Willkommen"

  - name: Add user jbond
    ipauser:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: jbond
      first: James
      last: Bond
      password: "Willkommen"

  - name: Add hmuster and jbond to admin user group
    ipagroup:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: admins
      user:
        - jdoe
        - jbond
        - admin

  - name: Add hmuster and jbond to superusers group
    ipagroup:
      ipaadmin_password: "{{ ipaadmin_password }}"
      name: superusers
      user:
        - jdoe
        - jbond


